import type { Metadata } from "next";

import "@/app/globals.css";
import Header from "@/comp/header/Header";
import Footer from "../../comp/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-dvh flex flex-col">
      <div>
        <Header></Header>
      </div>
      <div className="flex-1"> {children}</div>
      <Footer></Footer>
    </div>
  );
}
